direction: right

Server {
    docker-compose: {
        docker1: {

        }
        docker2: {
            
        }
        docker3: {
            
        }
        nginx: {

        }
    }

    
}


Client -- Server